# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-28 13:28
from __future__ import unicode_literals

import ImageClassifier.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModelBasicInfo',
            fields=[
                ('cn_name', models.CharField(max_length=20, null=True)),
                ('en_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('labels', models.TextField(max_length=65535, null=True)),
                ('algorithm', models.CharField(default='CNN-SVM', max_length=10)),
                ('accuracy', models.FloatField(null=True)),
                ('delete_status', models.IntegerField(choices=[(1, '已删除'), (0, '未删除')], default=0, verbose_name='删除状态')),
                ('public_status', models.IntegerField(choices=[(1, '已公开'), (0, '未公开')], default=0, verbose_name='公开状态')),
                ('train_status', models.IntegerField(choices=[(1, '已公开'), (0, '未公开')], default=0, verbose_name='训练状态')),
                ('model_type', models.IntegerField(choices=[(1, '普通模型'), (0, '合作模型')], default=1, verbose_name='模型类型')),
                ('data_create', models.DateTimeField(auto_now_add=True)),
                ('data_update', models.DateTimeField(auto_now=True)),
                ('user_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users')),
            ],
        ),
        migrations.CreateModel(
            name='LabelMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_labels', models.TextField(max_length=65535)),
                ('train_labels', models.TextField(max_length=65535)),
                ('model_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImageClassifier.ImageModelBasicInfo')),
            ],
        ),
        migrations.CreateModel(
            name='TrainData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgName', models.TextField(max_length=65535)),
                ('content', models.ImageField(null=True, upload_to=ImageClassifier.models.content_save_path)),
                ('label', models.TextField(max_length=65535)),
                ('delete_status', models.IntegerField(choices=[(1, '已删除'), (0, '未删除')], default=0, verbose_name='删除状态')),
                ('data_create', models.DateTimeField(auto_now_add=True)),
                ('data_update', models.DateTimeField(auto_now=True)),
                ('model_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImageClassifier.ImageModelBasicInfo')),
                ('user_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users')),
            ],
        ),
    ]
